version: '3.9'

services:

  database:
    container_name: technobot-mongodb
    image: mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER
      - MONGO_PASSWORD
      - MONGO_DATABASE
    healthcheck:
      test: [ "CMD-SHELL", "mongosh ${MONGO_DATABASE} -u ${MONGO_USER} -p ${MONGO_PASSWORD} --authenticationDatabase admin --eval 'db'" ]
      interval: 10s
      timeout: 10s
      retries: 30
    volumes:
      - ./database_init.sh:/docker-entrypoint-initdb.d/database_init.sh
      - mongodata:/data

  discord-bot:
    container_name: technobot
    build: ./
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    environment:
      - TOKEN
      - DATABASE=mongodb://$MONGO_USER:$MONGO_PASSWORD@technobot-mongodb

volumes:
  mongodata: